services:
  client:
    build: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
    depends_on:
      - server
    command: npm run dev -- --host

  server:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app

